name = "quizport"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
# 在 Cloudflare Dashboard 的 Pages/Workers 环境变量里设置私密变量

[[d1_databases]]
binding = "DB"
database_name = "quizport-db"
database_id = "445399e7-2966-446b-bcc9-5fde1d3ca3df"

[[kv_namespaces]]
binding = "QUIZPORT_KV"
id = "fd67b03432254d87ace803b481a38832"


